### ISSUE TITLE
Développement d’une méthode qui permet d’initialiser le fichier de configuration

### ISSUE THREAD

**Issue by Firas8** [JCERTIFLab/JCertif-Offline-Box#7]
Cette méthode a pour mission d’initialiser chaque paramètre avec une valeur par défaut, par la suite elle retourne ces paramètres sous forme d’un flux JSON.

Package : com.jcertif.offlinebox.configuration
Classe : OfflineBoxConfig.java

**Comment by Centonni** [comment]
Peut-être serait-il plus judicieux de définir une interface ou classe abstraite pour y définir les différentes méthodes concernant les issues #6 #5 #3 et #7, par exemple AbstractBoxConfiguration, pour laquelle une implémentation par défaut sera donnée, cela éviterait de créer ces demandes juste pour les méthodes d'une même classe.

**Comment by Firas8** [comment]
Je pense que l'utilisation d'une classe abstract est dans le but de généraliser du code en vu de le réutiliser dans plusieurs classe, si on applique ta proposition, je pense qu'on perdra l'utilité de la classe abstrait ou interface

**Comment by Centonni** [comment]
Cela permettrait de modifier les implémentations de manière transparente pour les autres classes qui en dépendraient par exemple, et aussi, il peut être tout à fait possible de proposer plusieurs implémentations pour la config.
Anyway allons seulement.

**Comment by setico** [comment]
Allons seulement ...

Le 5 mai 2015 21:19, Komi Serge Innocent notifications@github.com a écrit
:

> Cela permettrait de modifier les implémentations de manière transparente
> pour les autres classes qui en dépendraient par exemple, et aussi, il peut
> être tout à fait possible de proposer plusieurs implémentations pour la
> config.
> Anyway allons seulement.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/JCERTIFLab/JCertif-Offline-Box/issues/7#issuecomment-99226377
> .

## 

Best Regards,
Séti AFANOU

---

Twitter :  https://twitter.com/setico
Github :  https://github.com/setico
LinkedIn :  http://linkedin.com/pub/seti-afanou/47/95/318/
Setico, le développeur curieux!

---
